/* Sonobi - Morpheus version: 3.29.2 */
(function(){var x="function"==typeof Object.defineProperties?Object.defineProperty:function(t,l,n){t!=Array.prototype&&t!=Object.prototype&&(t[l]=n.value)},y="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function C(){C=function(){};y.Symbol||(y.Symbol=E)}var G=0;function E(t){return"jscomp_symbol_"+(t||"")+G++}
function H(){C();var t=y.Symbol.iterator;t||(t=y.Symbol.iterator=y.Symbol("iterator"));"function"!=typeof Array.prototype[t]&&x(Array.prototype,t,{configurable:!0,writable:!0,value:function(){return J(this)}});H=function(){}}function J(t){var l=0;return K(function(){return l<t.length?{done:!1,value:t[l++]}:{done:!0}})}function K(t){H();t={next:t};t[y.Symbol.iterator]=function(){return this};return t}function L(t){H();C();H();var l=t[Symbol.iterator];return l?l.call(t):J(t)}
function N(t){for(var l,n=[];!(l=t.next()).done;)n.push(l.value);return n}function O(t){return t instanceof Array?t:N(L(t))}function P(t,l){if(l){var n=y;t=t.split(".");for(var c=0;c<t.length-1;c++){var e=t[c];e in n||(n[e]={});n=n[e]}t=t[t.length-1];c=n[t];l=l(c);l!=c&&null!=l&&x(n,t,{configurable:!0,writable:!0,value:l})}}
P("Promise",function(t){function l(a){this.D=0;this.J=void 0;this.C=[];var b=this.F();try{a(b.resolve,b.reject)}catch(h){b.reject(h)}}function n(){this.C=null}function c(a){return a instanceof l?a:new l(function(b){b(a)})}if(t)return t;n.prototype.D=function(a){this.C||(this.C=[],this.H());this.C.push(a)};n.prototype.H=function(){var a=this;this.F(function(){a.L()})};var e=y.setTimeout;n.prototype.F=function(a){e(a,0)};n.prototype.L=function(){for(;this.C&&this.C.length;){var a=this.C;this.C=[];for(var b=
0;b<a.length;++b){var h=a[b];delete a[b];try{h()}catch(m){this.J(m)}}}this.C=null};n.prototype.J=function(a){this.F(function(){throw a;})};l.prototype.F=function(){function a(a){return function(g){h||(h=!0,a.call(b,g))}}var b=this,h=!1;return{resolve:a(this.pa),reject:a(this.H)}};l.prototype.pa=function(a){if(a===this)this.H(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof l)this.va(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;
default:b=!1}b?this.ca(a):this.L(a)}};l.prototype.ca=function(a){var b=void 0;try{b=a.then}catch(h){this.H(h);return}"function"==typeof b?this.wa(b,a):this.L(a)};l.prototype.H=function(a){this.U(2,a)};l.prototype.L=function(a){this.U(1,a)};l.prototype.U=function(a,b){if(0!=this.D)throw Error("Cannot settle("+a+", "+b|"): Promise already settled in state"+this.D);this.D=a;this.J=b;this.ba()};l.prototype.ba=function(){if(this.C){for(var a=this.C,b=0;b<a.length;++b)a[b].call(),a[b]=null;this.C=null}};
var a=new n;l.prototype.va=function(a){var b=this.F();a.za(b.resolve,b.reject)};l.prototype.wa=function(a,b){var h=this.F();try{a.call(b,h.resolve,h.reject)}catch(m){h.reject(m)}};l.prototype.then=function(a,b){function h(a,b){return"function"==typeof a?function(b){try{m(a(b))}catch(w){g(w)}}:b}var m,g,d=new l(function(a,b){m=a;g=b});this.za(h(a,m),h(b,g));return d};l.prototype.catch=function(a){return this.then(void 0,a)};l.prototype.za=function(c,b){function h(){switch(m.D){case 1:c(m.J);break;
case 2:b(m.J);break;default:throw Error("Unexpected state: "+m.D);}}var m=this;this.C?this.C.push(function(){a.D(h)}):a.D(h)};l.resolve=c;l.reject=function(a){return new l(function(b,h){h(a)})};l.race=function(a){return new l(function(b,h){for(var m=L(a),g=m.next();!g.done;g=m.next())c(g.value).za(b,h)})};l.all=function(a){var b=L(a),h=b.next();return h.done?c([]):new l(function(a,g){function d(b){return function(d){f[b]=d;p--;p||a(f)}}var f=[],p=0;do f.push(void 0),p++,c(h.value).za(d(f.length-1),
g),h=b.next();while(!h.done)})};return l});P("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991});P("Array.from",function(t){return t?t:function(l,n,c){H();n=n?n:function(a){return a};var e=[],a=l[Symbol.iterator];if("function"==typeof a)for(l=a.call(l);!(a=l.next()).done;)e.push(n.call(c,a.value));else{a=l.length;for(var q=0;q<a;q++)e.push(n.call(c,l[q]))}return e}});
P("Object.assign",function(t){return t?t:function(l,n){for(var c=1;c<arguments.length;c++){var e=arguments[c];if(e)for(var a in e)Object.prototype.hasOwnProperty.call(e,a)&&(l[a]=e[a])}return l}});P("Array.prototype.find",function(t){return t?t:function(l,n){a:{var c=this;c instanceof String&&(c=String(c));for(var e=c.length,a=0;a<e;a++){var q=c[a];if(l.call(n,q,a,c)){l=q;break a}}l=void 0}return l}});P("Object.is",function(t){return t?t:function(l,n){return l===n?0!==l||1/l===1/n:l!==l&&n!==n}});
P("Array.prototype.includes",function(t){return t?t:function(l,n){var c=this;c instanceof String&&(c=String(c));var e=c.length;for(n=n||0;n<e;n++)if(c[n]==l||Object.is(c[n],l))return!0;return!1}});
P("String.prototype.includes",function(t){return t?t:function(l,n){if(null==this)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(l instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return-1!==(this+"").indexOf(l,n||0)}});
(function(t,l){(function(n){function c(a){if(e[a])return e[a].ra;var q=e[a]={ld:a,wc:!1,ra:{}};n[a].call(q.ra,q,q.ra,c);q.wc=!0;return q.ra}var e={};c.H=n;c.F=e;c.C=function(a,e){c.D(a)||Object.defineProperty(a,"a",{configurable:!1,enumerable:!0,get:e})};c.J=function(a){var e=a&&a.Nc?function(){return a["default"]}:function(){return a};c.C(e,e);return e};c.D=function(a){return Object.prototype.hasOwnProperty.call(a,"a")};c.L="";return c(c.U=7)})([function(n,c,e){function a(a){var b={};a.forEach(function(a){b[a.K]=
b[a.K]||[];b[a.K]=b[a.K].concat(a)});return b}function q(){return v.a.location.origin?v.a.location.origin:v.a.location.origin=v.a.location.protocol+"//"+v.a.location.hostname+(v.a.location.ia?":"+v.a.location.ia:"")}function b(a){var b=!1;return function(d){for(var f=[],F=0;F<arguments.length;++F)f[F-0]=arguments[F];if(!b){b=!0;try{a.apply(a,f)}catch(I){}}}}function h(a){a=void 0===a?[]:a;if(!Array.isArray(a))return[];a=Array.from(a);for(var b=a.length;b;b--){var d=Math.floor(Math.random()*b),f=L([a[d],
a[b-1]]);a[b-1]=f.next().value;a[d]=f.next().value}return a}function m(a,b){b=void 0===b?M().location:b;b=decodeURI(b);a=a.replace(/[\[\]]/g,"\\$&");return(a=(new RegExp("[?&]"+a+"(=([^&#]*)|&|#|$)")).exec(b))?a[2]?decodeURIComponent(a[2].replace(/\+/g," ")):"":null}function g(a){return parseInt(a,10)}function d(a,b,f){var g;if(!b||"string"!==typeof b)return"function"===typeof f?f():f;if(-1!==b.indexOf(".")){f=b.split(".");b=!1;for(var k=0;k<f.length;k++){if("object"!==typeof a){b=!0;break}a=d(a,
f[k])}b||(g=a);return g}k="get"+b[0].toUpperCase()+b.slice(1);b=a&&"function"===typeof a[k]?k:b;a&&(a.hasOwnProperty(b)||"function"===typeof a[b])&&(g=a[b]);void 0===g&&(g=f);"function"===typeof g&&(g=g());return g}function f(a){return a?'<script type="text/javascript" src="'+a+'">\x3c/script>':""}function p(a,b){if(!a)return"";b=b.split("x");return'<iframe id="'+u()+'" width="'+b[0]+'" '+('height="'+b[1]+'" marginwidth="0" marginheight="0" ')+('style="border:0" frameborder="0" src="'+a+'" border="0" ')+
'scrolling="no" vspace="0" hspace="0"></iframe>'}function k(a){return a?'<div style="position:absolute;left:0px;top:0px;visibility:hidden;">'+('<img src="'+a+'"></div>'):""}function w(a,b){var d=[];a.forEach(function(a){-1!==b.indexOf(a)&&d.push(a)});return d}function z(){return[v.a.innerWidth||v.a.document.documentElement.clientWidth||v.a.document.body.clientWidth,v.a.innerHeight||v.a.document.documentElement.clientHeight||v.a.document.body.clientHeight]}function B(a,b){a=Math.round(a);for(var d=
0;d<b.length;d++){var f="lt"in b[d]&&a<b[d].lt||!("lt"in b[d]);!("ge"in b[d]&&a>=b[d].ge)&&"ge"in b[d]||!f||"percent"in b[d]&&(a*=b[d].percent)}for(d=0;d<b.length;d++)f="lt"in b[d]&&a<b[d].lt||!("lt"in b[d]),!("ge"in b[d]&&a>=b[d].ge)&&"ge"in b[d]||!f||("set"in b[d]?a=b[d].set:"round"in b[d]&&(a=Math.floor(a)-Math.floor(a)%b[d].round));return a}function r(a,b,d){Object.keys(b).forEach(function(f){a=a.replace(d+f+d,b[f])});return a}function u(){return t()+Math.random().toString(16).substr(2)}function M(a){a=
void 0===a?"":a;var b=v.a.document.createElement("a");b.href=a||v.a.location;return{location:b.href,href:b.href,protocol:b.protocol,hostname:b.hostname,host:b.host,ia:b.ia,pathname:b.pathname,search:b.search,la:b.la,origin:b.origin}}function D(a){return Object.keys(a).map(function(b){return Array.isArray(a[b])?a[b].map(function(a){return b+"[]="+a}).join("&"):b+"="+a[b]}).join("&")}c.g=D;var v=e(1),l=e(2),t=function(){var a=0;return function(){a++;return a}}();c.j=u;c.n=r;n={highestCPMWins:function(a,
b){if(0===a.length)return null;for(var d={I:0},f=0;f<a.length;f++)d.I>=a[f].I?b.log("sbi",l.q,[a[f].I,a[f].P]):d=a[f];return d.I?d:null},sonobiDealWinsOverHighestCPM:function(a,b){if(0===a.length)return null;for(var d={I:0,P:null,W:null},f=0;f<a.length;f++)if(10<=a[f].ka)a[f].I>d.I&&(b.log("sbi",l.q,[d.I,d.P]),d=a[f]);else{if("sonobi"===a[f].P&&a[f].W){d=a[f];a.forEach(function(g){g!==d&&b.log("sbi",l.q,[a[f].I,a[f].P])});break}d.I>=a[f].I?b.log("sbi",l.q,[a[f].I,a[f].P]):d=a[f]}return d.I||d.W?d:
null},lowestDealPriorityWinsOverHighestCPM:function(a,b){if(0===a.length)return null;a.sort(function(a,b){return a.ka-b.ka});var d=a[0].ka,f=a.filter(function(a){return a.ka===d});a={I:0,P:null,W:null};f=L(f);for(var g=f.next();!g.done;g=f.next())g=g.value,a.I>=g.I?b.log("sbi",l.q,[g.I,g.P]):a=g;return a.I||a.W?a:null}};c.a=n;c.b=B;c.k=z;c.f=w;c.l=d;c.i=m;c.c=h;c.m=b;c.h=q;c.d=a;c.e={bd:function(a,b){return a.reduce(function(a,d){return a.then(function(a){return b(d).then(a.push.bind(a)).then(function(){return a})})},
Promise.resolve([]))},N:M,Za:u,gd:function(a){if(a){try{var b=a.contentWindow?a.contentWindow.document:a.pb.document?a.pb.document:a.pb}catch(S){return}return b}},fd:function(){var a=v.a.document.createElement("iframe");a.id=u();a.height=0;a.width=0;a.hspace="0";a.vspace="0";a.marginWidth="0";a.marginHeight="0";a.style.border="0";a.frameBorder="0";a.border="0px";a.scrolling="no";a.src="about:blank";a.style.display="none";return a},wd:r,rd:function(a,b){for(var d=0,f=a.length>b.length?b.length:a.length,
g=a.length<b.length?b.length:a.length,k=0;k<f;k++)a[k]===b[k]&&d++;return d/g},Mc:n,Oc:B,kd:z,Zc:w,cd:D,mc:function(a){try{var b=new RegExp(a,"i"),d=v.a.performance.getEntriesByType("resource").filter(function(a){return b.test(a.name)});return Array.isArray(d)?Math.max(d[d.length-1].Xc||0,0):null}catch(A){return null}},ab:function(a){return void 0!=={sizes:1,timeout:1}[a]},Da:function(a){var b=v.a.innerWidth,d=null,f;for(f in a)if(a.hasOwnProperty(f)){var g=a[f].viewport.lt||Number.MAX_SAFE_INTEGER;
if(b>=(a[f].viewport.ge||0)&&b<g){d=f;break}}return d},rc:function(a,b){return a.reduce(function(a,d){(a[d[b]]=a[d[b]]||[]).push(d);return a},{})},Vc:k,Tc:p,Uc:f,ec:function(a,b,d){switch(void 0===b?"SCRIPT":b){case "SCRIPT":return f(a);case "IFRAME":return p(a,void 0===d?"1x1":d);case "TRACK":return k(a);case "SCRIPT_BLOCK":return a?'<script type="text/javascript">'+a+"\x3c/script>":"";default:return""}},Z:d,Sc:function(a){var b=/^\d{1,4}x\d{1,4}$/;return"string"===typeof a&&b.test(a)?a.split("x").map(g):
a},Ac:function(a,b){var d={},f;for(f in a)-1===b.indexOf(f)&&(d[f]=a[f]);return d},zb:function(a){try{return"string"!==typeof a?void 0:v.a.document.cookie.split("; ").reduce(function(a,b){var d=L(b.split("="));b=d.next().value;d=N(d);a[b]=d.join("=");return a},{})[a]}catch(R){}},nc:m,Pc:h,Gc:function(a){void 0!==v.a.performance&&"function"===typeof v.a.performance.setResourceTimingBufferSize&&v.a.performance.setResourceTimingBufferSize(a)},$:b,tc:function(a,b){a=void 0===a?[]:a;b=void 0===b?[]:b;
return Array.isArray(a)&&Array.isArray(b)?a.reduce(function(a,d){-1===a.indexOf(d)&&-1<b.indexOf(d)&&a.push(d);return a},[]):[]},ub:function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;return("x"===a?b:b&3|8).toString(16)})},vc:function(a,b){var d={},f;for(f in a)-1!==b.indexOf(f)&&(d[f]=a[f]);return d},ed:q,Rc:a}},function(n,c,e){n=e(11);e=window;Object(n.a)(e);c.a=e},function(n,c){c.x=200001;c.n=200003;c.A=200005;c.w=200006;c.d=200008;c.m=
200009;c.e=200011;c.k=200012;c.q=200017;c.B=200019;c.o=200020;c.f=200022;c.c=200023;c.b=200024;c.a=200025;c.g=200026;c.y=200027;c.z=200028;c.s=200029;c.i=200030;c.h=200031;c.v=200032;c.t=200033;c.l=200034;c.j=200035;c.p=200036;c.r=200039;c.u=200040},function(n,c,e){function a(a){return a?a.replace(/^\?/,"").split("&").reduce(function(a,b){var d=L(b.split("="));b=d.next().value;d=d.next().value;/\[\]$/.test(b)?(b=b.replace("[]",""),a[b]=a[b]||[],a[b].push(d)):a[b]=d||"";return a},{}):{}}function q(b){var d=
h.a.document.createElement("a");d.href=decodeURIComponent(b);return{protocol:(d.protocol||"").replace(/:$/,""),hostname:d.hostname,ia:+d.ia,pathname:d.pathname,search:a(d.search||""),la:(d.la||"").replace(/^#/,""),host:d.host}}function b(a){return(a.protocol||"http")+"://"+(a.host||a.hostname+(a.ia?":"+a.ia:""))+(a.pathname||"")+(a.search?"?"+Object(m.g)(a.search||""):"")+(a.la?"#"+a.la:"")}var h=e(1),m=e(0);c.a={Lc:3E4,qd:function(a,b,f,p){var d=this;f=void 0===f?"sbi_"+Object(m.j)():f;p=void 0===
p?{}:p;a=a.replace("%%callback%%",f);return new Promise(function(g){var k=h.a.setTimeout(g,d.Lc,p),c,r=Object(m.m)(function(a){h.a.clearTimeout(c);h.a.clearTimeout(k);if(null==b)g(a);else{var d={};d[b]=a;g(d)}});h.a[f]=r;d.Aa("script",{src:a}).then(function(){c=h.a.setTimeout(function(){r(p)},500)})})},Sa:function(a,d,f){f=void 0===f?{Db:"GET",withCredentials:!1,Bc:!1,dc:"text/plain"}:f;return new Promise(function(g,k){function m(){4===r.readyState&&(200<=r.status&&400>r.status?g(r.responseText):
k({status:r.status,statusText:r.statusText}))}var p=f.Db||(d?"POST":"GET"),c=h.a.XDomainRequest&&(!h.a.XMLHttpRequest||void 0===(new h.a.XMLHttpRequest).responseType);if(c){var r=new h.a.XDomainRequest;r.onload=function(){g(r.responseText)};r.onerror=function(){k("xhr on error")};r.ontimeout=function(){k("xhr timeout")};r.onprogress=function(){}}else r=new h.a.XMLHttpRequest,r.onreadystatechange=m;if("GET"===p&&d){var u=q(a);Object.assign(u.search,d);a=b(u)}r.open(p,a);c||(f.withCredentials&&(r.withCredentials=
!0),f.Bc&&r.setRequestHeader("X-Requested-With","XMLHttpRequest"),r.setRequestHeader("Content-Type",f.dc||"text/plain"));r.send("POST"===p&&d)})},Aa:function(a,b){return new Promise(function(d,g){if("image"===a)var f=Object.assign(new h.a.Image,b);else if("script"===a||"iframe"===a)f=h.a.document.createElement(a),Object.keys(b||{}).forEach(function(a){f[a]=b[a]}),h.a.document.head.appendChild(f);else{g();return}f.addEventListener?f.addEventListener("load",function(){d()}):f.readyState?f.onreadystatechange=
function(){3===f.readyState&&d()}:g()})}}},function(n,c){function e(){this.C={}}e.prototype.fa=function(a,c){for(var b=[],h=1;h<arguments.length;++h)b[h-1]=arguments[h];a in this.C&&(this.C[a].T.forEach(function(a){return a.apply(a,b)}),this.C[a].$.forEach(function(a){return a.apply(a,b)}),this.C[a].$=[])};e.prototype.$=function(a,c){this.C[a]=this.C[a]||{T:[],$:[]};this.C[a].$.push(c)};e.prototype.T=function(a,c){this.C[a]=this.C[a]||{T:[],$:[]};this.C[a].T.push(c)};e.prototype.Dc=function(a,c){this.C[a].T=
this.C[a].T.filter(function(a){return a!==c});this.C[a].$=this.C[a].T.filter(function(a){return a!==c})};c.a=new e;c.b=new e},function(n,c){function e(a){this.S=a.globalSettings}e.prototype.ga=function(a){return(a=void 0===a?null:a)?this.S[a]:this.S};c.a=e},function(n,c,e){function a(a){this.S=a.platformSettings;this.X=new q.a(a)}var q=e(5),b=e(0);a.prototype.sa=function(a,c){a=void 0===a?null:a;c=void 0===c?null:c;return a?(a=this.S[a],c&&(a=a[c],a=b.e.ab(c)&&!a?this.X.ga(c):a),a):this.S};c.a=a},
function(n,c,e){n.ra=e(8)},function(n,c,e){Object.defineProperty(c,"__esModule",{value:!0});n=e(9);e=e(1);c["default"]=Object(n.a)(e.a,t,l)},function(n,c,e){var a=e(10),q=e(12),b=e(14),h=e(23),m=e(24),g=e(26),d=e(27),f=e(0),p=e(28);c.a=function(k,c,e){if(!k.hasOwnProperty("sbi_km")||!k.sbi_km.apiReady){f.e.Gc(500);var z=k.sbi_morpheus=Object(d.a)();c=k.sbi_km=Object.assign({API:{},config:c,apiReady:!1,id:f.e.Za()},k.sbi_km);var r=new m.a(c.config),u=new a.a(c.config),w=new h.a(u,r),D=new b.a(u,w,
r);D.sc(c.config);c.API=Object.assign(c.API,{debug:u.fc.bind(u),getLog:u.xb.bind(u)});u=new q.a(u,c.config,D,w);(new p.a(D,u,r)).Cc();r=Object(g.a)(D,c.config,r.X.ga("timeout"),u,r,w);u.Kc(r.Ec);-1===k.location.search.indexOf("sbi_test")?k.document.cookie="sbi_debug=false":-1!==k.document.cookie.indexOf("sbi_debug=true")?c.API.debug(!0):-1!==k.location.search.indexOf("sbi_test")&&(k.document.cookie="sbi_debug=true",c.API.debug(!0));z.initialize();k.sbi_km.apiReady=!0;k.sbi_km.version=e}}},function(n,
c,e){function a(a,g){var d=this;g=void 0===g?b.a:g;this.log=function(a,b,g,c){null!=c?c-=d.navigationStart:c=0+q.a.performance.now();a={dateTime:c,time:c-0,id:b,service:a,replacements:g};a.Ib=g||[];h.push(a);d.C&&"logData"in q.a.sbi_km&&(g=q.a.sbi_km.logData,d.D(g[a.id].service,a.ib,g[a.id].template,a.Ib))};this.caller=g;this.config=a;this.C=!1;this.navigationStart=q.a.performance.timing.navigationStart}var q=e(1),b=e(3),h=[];a.prototype.xb=function(){h.sort(function(a,b){return a.ib-b.ib});return h};
a.prototype.F=function(a,b){for(var d=[],f=1;f<arguments.length;++f)d[f-1]=arguments[f];q.a.console.log.apply(q.a.console,[].concat(["sonobi",a],O(d)))};a.prototype.D=function(a,b,d,f){var g=[a,b];a=d.apply(d,f);Array.isArray(a)?a.forEach(function(a){return g.push(a)}):g.push(a);q.a.console.log.apply(q.a.console,g)};a.prototype.fc=function(){var a=this;this.C=!0;b.a.Aa("script",{src:this.config.url+"/morpheus_console.js"}).then(function(){var b=q.a.sbi_km.logData;a.xb().forEach(function(d){a.D(b[d.id].service,
d.ib,b[d.id].template,d.Ib)})}).catch(function(b){a.F((new Date).toLocaleString(),"error in debug output",b)})};c.a=a},function(n,c){c.a=function(c){(function(a){var c=Date.now();"performance"in a||(a.performance={});"timing"in a.performance?a.performance.timing.navigationStart&&(c=a.performance.timing.navigationStart):a.performance.timing={navigationStart:c};"now"in a.performance||(a.performance.now=function(){return Date.now()-c})})(c);Object.assign||Object.defineProperty(Object,"assign",{enumerable:!1,
configurable:!0,writable:!0,value:function(a){if(void 0===a||null===a)throw new TypeError("Cannot convert first argument to object");for(var c=Object(a),b=1;b<arguments.length;b++){var h=arguments[b];if(void 0!==h&&null!==h)for(var e=Object.keys(Object(h)),g=0,d=e.length;g<d;g++){var f=e[g],p=Object.getOwnPropertyDescriptor(h,f);p&&p.enumerable&&(c[f]=h[f])}}return c}})}},function(n,c,e){function a(a,c,k,e){var f=this;this.eb=function(a,d,c,k){var u=Date.now(),p=Object.assign({},f.da.ea),r=p[Object.keys(p).find(function(a){a=
p[a];return a.id===d&&!a.ma})];if(!r)return Promise.reject("Could not find winning bid");var e=f.C[r.K];if(!e)return Promise.reject("Could not find a slot for the winning bid");e.Gb[r.id]=u;return f.D.eb(e,a,r.qa,c,k,r.size).then(function(a){var b=Object.keys(a.Gb);b=f.da.ea[b[0]];f.G.log("sbi",g.B,[b.I,b.P]);b.ma=!0;r.db=3;f.Y.oa([b]);a.kb=null}).catch(function(a){b.a.console.log(a);f.G.log("sbi",g.u,[a])})};this.pc=function(){var a={Wa:!1};if("object"!==typeof a)return f.C;a.$a=!1;return Object.keys(f.C).reduce(function(b,
d){var c=f.C[d],g;for(g in a)if(c[g]!==a[g])return b;b[d]=c;return b},{})};this.ic=function(a){if("object"===typeof a)return a.$a=!1,f.C[Object.keys(f.C).find(function(b){b=f.C[b];for(var d in a)if(b[d]!==a[d])return!1;return!0})]};this.Kc=function(a){f.H=a};this.J=function(a){var b={};a=L(a);for(var d=a.next();!d.done;d=a.next()){d=f.D.Ea(d.value);var c=null,g;for(g in f.C)if(f.C[g].O===d){c=f.C[g].id;break}null!=c&&(b[c]=f.C[c])}return b};this.F=function(a){var b={},d={};a.forEach(function(a){var c=
f.D.Ea(a),g=f.D.yb(a);if(!(c in d)){b[g]=b[g]++||1;var k=Object(h.j)();d[k]={K:g,zd:g+":"+b[g],gc:"google_ads_iframe_"+a.getSlotId().getId(),O:c,id:k,xd:!1,pd:!1,$a:!1,Gb:{},ea:[],kb:null,na:f.D.vb(a),Ja:{},od:f.D.lc(a),Ga:f.D.vb.bind(f.D,a),jd:a.getTargetingMap.bind(a),Wa:!1,rb:!1,Qc:0,uc:q}}});f.C=Object.assign(f.C,d)};this.Ic=function(a){for(var b in a)if(b in f.C){var d=f.C[b].O;f.C[b].kb=a[b];f.C[b].Ja=a[b].targeting;var c=Object.assign({},f.da.ea)[a[b].id];c&&(c.qa=a[b].creative,c.size=a[b].size,
c.Ja=a[b].targeting,f.C[b].Ja.sbi_size=a[b].size,f.D.Hc(d,a[b].targeting))}};var p=this;this.G=a;this.config=c;this.C={};this.da=k;this.Y=e;this.D=new m.a(this.G,this);b.a.sbi_km.API.render=this.eb;d.a.$("initialized",function(a,b){p.G.log("sbi",g.n,[a]);p.F(a);"function"===typeof b&&b();d.a.T("slotsDefined",function(a){p.G.log("sbi",g.y,[a]);p.F(a)})});d.a.T("slotsDestroyed",function(a){a.forEach(function(a){var b=p.D.Ea(a);a=p.D.yb(a);for(var d in p.C)p.C[d].O===b&&p.C[d].K===a&&(p.C[d].$a=!0,p.G.log("sbi",
g.z,[p.C[d]]))},this)});d.a.T("slotsRequestingRender",function(a){var b=p.J(a.R);p.H(b,a.done)})}function q(a){a=void 0===a?this:a;if(-1<a.O.indexOf(" ")||1>a.na.length)return!1;var b=/^([a-zA-Z0-9\/_.*\\!<:()-]+)$/;return a.K&&b.test(a.K)?!0:!1}var b=e(1),h=e(0),m=e(13),g=e(2),d=e(4);a.prototype.H=function(){};y.Object.defineProperties(a.prototype,{R:{configurable:!0,enumerable:!0,get:function(){return this.C},set:function(a){this.C=a}}});c.a=a},function(n,c,e){function a(a,f){this.D=!1;var d=this;
this.D=!1;this.H=this.va=Function;this.wa={};this.C={};this.G=a;this.J=[];this.pa=f;b.a.googletag=b.a.googletag||{};b.a.googletag.cmd=b.a.googletag.cmd||[];if(b.a.googletag.pubadsReady)a.log("sbi",g.r);else{a=this.Rb();var c=!1;b.a.googletag.cmd[a](function(){c||(c=!0,d.wa=b.a.googletag,d.C=d.wa.pubads(),d.Vb(),d.Ub())});!1!==Object(m.l)(f.config,"globalSettings.osEnabled")&&q(a,b.a.googletag.cmd);this.L={md:!1,Ua:!1,sb:!1};this.U={}}}function q(a,f){f=void 0===f?b.a.googletag.cmd:f;if("u"===a[0]){var d=
f.splice;f[a]=function(a){d.apply(f,[1,0,a]);return this.length};f.splice=function(){var a=f.shift();d.apply(f,arguments);return d.apply(f,[0,0,a])}}}var b=e(1),h=e(4),m=e(0),g=e(2);a.prototype.Rb=function(){return null!=b.a.googletag.cmd.length?"unshift":"push"};a.prototype.Xb=function(a,b,c){c?a.postMessage({creative:b,message:"SBI_RENDER"},c):a.document.write(b)};a.prototype.Yb=function(a,f,c,k,e,h,m){k=k.split("x");var d=parseInt(k[0],10),p=parseInt(k[1],10);if(this.Qb(a,d,p))if(h)Array.from(b.a.document.getElementById(f).getElementsByTagName("div")).filter(function(a){return-1<
a.id.indexOf("google_ads_iframe")}).forEach(function(a){var b=a.childNodes[0];b.width=d.toString();b.height=p.toString();a.style.width=d+"px";a.style.height=p+"px";c.postMessage({creative:e,message:"SBI_RENDER"},h)});else{if(c.inDapIF)try{var w=b.a.document.getElementsByName(c.frameElement.name)[0];w.width=d.toString();w.height=p.toString()}catch(D){this.G.log("sbi",g.k)}c.document.write(e)}else m(a)};a.prototype.Wb=function(a){var b=this;return function(d){var f=b.F(a.O);b.ba(f);b.H.apply(b.C,[[f],
{changeCorrelator:!1}]);throw d;}};a.prototype.eb=function(a,b,c,k,e,h){var d=this,f=this;return(new Promise(function(p,m){f.G.log("sbi",g.v,[a]);a.rendering=!0;var u=c;k&&Object.keys(k).forEach(function(a){Array.isArray(k[a])||(k[a]=[k[a]]);u=u.replace("%%"+a+"%%",k[a].join(","))});if(d.pa.config.globalSettings.supportResizing){var r=d.F(a.O);d.Yb(r,a.O,b,h,u,e,m)}else d.Xb(b,u,e);f.G.log("sbi",g.t,[a]);p(a)})).catch(this.Wb(a))};a.prototype.ba=function(a){var b=a.getTargetingMap();b=Object.keys(b).filter(function(a){return"sbi"===
a.substr(0,3)});0<b.length&&b.forEach(function(b){a.clearTargeting(b)})};a.prototype.F=function(a){var b=this;return this.ca().find(function(d){return b.Ea(d)===a})||null};a.prototype.Ea=function(a){return a&&"getSlotElementId"in a?a.getSlotElementId():null};a.prototype.ca=function(){return this.C.getSlots()};a.prototype.yb=function(a){return a.getAdUnitPath()};a.prototype.Qb=function(a,b,c){var d=!1;this.Ga(a).forEach(function(a){d=d||a.Ob===b&&a.Ab===c});return d};a.prototype.vb=function(a){return this.Ga(a).map(function(a){return a.Ob+
"x"+a.Ab})};a.prototype.Ga=function(a){a=a.getSizes.apply(a,Object(m.k)());a=Array.isArray(a)?a:[];return a.filter(function(a){return"function"===typeof a.getWidth}).map(function(a){return{Ob:a.getWidth(),Ab:a.getHeight()}})};a.prototype.Hc=function(a,b){if(a=this.F(a))for(var d in b)d&&b[d]&&a.setTargeting(d,b[d])};a.prototype.Vb=function(){var a=this,f=b.a.googletag.enableServices;b.a.googletag.enableServices=function(){var d=this,c=arguments;a.G.log("sbi",g.h);a.D||(a.D=!0,h.a.fa("initialized",
a.ca(),function(){f.apply(d,c);a.G.log("sbi",g.l,[a.J.toString()]);a.J.forEach(function(a){return b.a.googletag.display(a)});a.J=[]}))};var c=this.C.enableSingleRequest;this.C.enableSingleRequest=function(){a.D||(a.L.sb=!0);c.apply(this,arguments)};var k=this.C.disableInitialLoad;this.C.disableInitialLoad();a.Ua=k;this.C.disableInitialLoad=function(){a.Sb||(a.L.Ua=!0);k.apply(this,arguments)}};a.prototype.Ub=function(){function a(a){if(a&&Object.keys(a).length){var b=Object(m.j)();c.U[b]={};for(var d in a)a[d].Wa=
!0;c.U[b]=a;d=Object.keys(a).map(function(b){return c.F(a[b].O)});for(var f=L(d),e=f.next();!e.done;e=f.next())c.ba(e.value);var p={R:d,done:function(){var a=k.U[b],d=Object.keys(a).map(function(b){return k.F(a[b].O)});k.G.log("sbi",g.s,[p.R]);k.H.apply(k.C,[d,{changeCorrelator:!1}])}};h.a.fa("slotsRequestingRender",p)}}function f(a){c.va.apply(b.a.googletag,a)}var c=this,k=this,e=b.a.googletag.defineSlot;b.a.googletag.defineSlot=b.a.googletag.defineUnit=function(){"/"!==arguments[0].charAt(0)&&(arguments[0]=
"/"+arguments[0]);var a=e.apply(this,arguments);if(a){var b=a.getAdUnitPath;a.getAdUnitPath=function(a){a=b.call(this,a);return("/"!==a.charAt(0)?"/":"")+a};k.D&&h.a.fa("slotsDefined",[a])}return a};var z=b.a.googletag.defineOutOfPageSlot;b.a.googletag.defineOutOfPageSlot=function(){"/"!==arguments[0].charAt(0)&&(arguments[0]="/"+arguments[0]);var a=z.apply(this,arguments);if(a){var b=a.getAdUnitPath;a.getAdUnitPath=function(a){a=b.call(this,a);return("/"!==a.charAt(0)?"/":"")+a};a.isOutOfPage=!0;
k.D&&h.a.fa("slotsDefined",[a])}return a};var q=b.a.googletag.destroySlots;b.a.googletag.destroySlots=function(){var a=q.apply(this,arguments);if(a){var b=arguments.length?arguments[0].filter(function(a){return k.Tb(a)}):k.C.getSlots();h.a.fa("slotsDestroyed",b)}return a};this.H=this.C.refresh;this.C.refresh=function(){var a=Array.from(arguments),b={};0<a.length&&Array.isArray(a[0])?0===a[0].length?b.R=[]:(b.R=[],a[0].forEach(function(a){a&&"object"===typeof a&&"function"===typeof a.getSizes?b.R.push(a):
k.G.log("sbi",g.p,[a])})):b.R=k.ca();b.done=function(){k.G.log("sbi",g.s,[b.R]);k.H.apply(k.C,a)};b.R.forEach(function(a){k.ba(a)});h.a.fa("slotsRequestingRender",b)};this.va=b.a.googletag.display;b.a.googletag.display=function(b){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];c.Sb=!0;e=0<d.length&&("string"===typeof d[0]||"object"===typeof d[0]);var k=d[0];"object"===typeof k&&(k=k.id);k=c.pa.ic({O:k||""});var h=c.pa.pc(),m=!!k,p=c.L.Ua,w=c.L.sb,r=m&&!0===k.rb;c.D?m&&e?r||(k.rb=!0,f(d),
p||(w?a(h):(d=k,d.Wa=!0,c.G.log("sbi",g.i,[d]),d=c.F(d.O),c.C.refresh([d],{changeCorrelator:!1})))):f(d):(c.G.log("sbi",g.j,[d[0]]),c.J.push(d[0]))}};a.prototype.lc=function(a){return a.hasOwnProperty("isOutOfPage")&&a.isOutOfPage};a.prototype.Tb=function(a){try{return"function"===typeof a.dd}catch(f){return!1}};c.a=a},function(n,c,e){function a(a,c,e){var f=this;this.sc=function(a){a.adapterSettings.forEach(function(c){var g=c.name;c=new b.a(a,g);var e=d.a[g];c.Ba&&(f.C[g]={ja:e,Q:c},f.G.log("sbi",
m.e,[g]),f.C[g].Jc=e.ua(c,f.Y,f.G).then(function(a){f.G.log("sbi",m.f,[g]);return a}))})};this.L=function(a){var b={};Object.keys(a).forEach(function(d){a[d].forEach(function(a){b[a.id]=a})});f.D=Object.assign(f.D,b);return b};this.Jb=function(a,b,d,c){f.G.log("sbi",m.x,[b]);f.G.log("sbi",m.w);var e=Object.keys(f.C).map(function(a){return{da:f.C[a],Ka:!1}});f.F[d]=new g.a(d,e,a,b,f.G,f.Y);f.F[d].ua(function(a){c(f.L(a))})};this.J=function(a,b){var d=a.reduce(function(a,b){a[b.P]=a[b.P]||[];a[b.P].push(b);
return a},{});return Object.keys(d).reduce(function(a,c){var g=q.a.sonobiDealWinsOverHighestCPM(d[c],f.G);g&&(a["sbi_"+c+"_price"]=Object(q.b)(g.I,b),a["sbi_"+c+"_size"]=g.size);return a},{})};this.qc=function(a,b,d){if(0===a.length)return{};a=Object(q.d)(a);for(var c={},g=L(Object.keys(a)),e=g.next();!e.done;e=g.next())if(e=e.value,0!==a[e].length){var k=q.a.sonobiDealWinsOverHighestCPM(a[e],f.G);if(null!=k){k.lb=!0;c[e]={targeting:{}};c[e].id=k.id;f.H.X.ga().widgetRender&&(c[e].targeting.sbi_lookup_id=
h.a.sbi_km.id);c[e].targeting.sbi_kmid=k.id;c[e].targeting.sbi_bidder=k.P;c[e].targeting.sbi_ct=k.jb;var p=Object(q.b)(k.I,b);"number"===typeof p&&0<p&&(c[e].targeting.sbi_price=p);for(var n in k.Va)c[e].targeting[n]=k.Va[n];p=k.qa;p=Object(q.n)(p,k.Cb,"%%");c[e].creative=p;c[e].size=k.size;d&&(c[e].targeting=Object.assign(c[e].targeting,f.J(a[e],b)))}}f.G.log("sbi",m.A,[c]);return c};this.G=a;this.D={};this.Y=c;this.C={};this.H=e;this.F={}}var q=e(0),b=e(15),h=e(1),m=e(2),g=e(16),d=e(17);y.Object.defineProperties(a.prototype,
{ea:{configurable:!0,enumerable:!0,get:function(){return this.D},set:function(a){this.D=a}}});c.a=a},function(n,c,e){function a(a,c){var d=this;this.J=b;this.H=h;this.Ya=function(a){var b=a.bb;a=d.D[void 0===a.M?d.M:a.M];b&&(a=a[b],a=g.e.ab(b)&&!a?d.aa.sa(g.e.Da(d.aa.sa()),b):a);return a};if(!c)throw Error("Provide an adapter name in your AdapterSettingsConfigInterface constructor.");this.S=a.adapterSettings;this.aa=new m.a(a);this.D=q(this.S);this.M=c;this.C=this.D[c]}function q(a){for(var b={},
d=0;d<a.length;d++)b[a[d].name]=a[d];return b}function b(a,b,c){a=g.e.Z(a,void 0===c?"dimensions.platforms":c)||[];return"*"===b||0===a.length||-1<a.indexOf("*")?!0:-1<a.indexOf(b)}function h(a,b){b=void 0===b?"dimensions.domains":b;var d=g.e.N().location;a=g.e.Z(a,b)||[];if(0===a.length||-1<a.indexOf("*"))return!0;if("string"===typeof a)return(new RegExp(a)).test(d);for(b=0;b<a.length;b++)if((new RegExp(a[b])).test(d))return!0;return!1}var m=e(6),g=e(0);a.prototype.Fa=function(a){var b=a.name;return this.F({M:void 0===
a.M?this.M:a.M,V:void 0===a.V?"requestSettings":a.V}).find(function(a){return a.name===b})};a.prototype.oc=function(){return(this.ha({name:"protocol"})||"https").replace(":","").replace("//","")};a.prototype.ha=function(a){return(a=this.Fa({name:a.name,V:void 0===a.V?"requestSettings":a.V,M:void 0===a.M?this.M:a.M}))?a.value:void 0};a.prototype.F=function(a){var d=[];a=this.D[void 0===a.M?this.M:a.M][void 0===a.V?"requestSettings":a.V]||[];for(var c=0;c<a.length;c++){var e=a[c];if(e.hasOwnProperty("dimensions")){var m=
"*";this.aa.S&&(m=g.e.Da(this.aa.sa()));h(e)&&b(e,m)&&d.push(e)}else d.push(e)}return d};a.prototype.yc=function(a){var b=a.K,d=void 0===a.Bb?"placementid":a.Bb;a=this.F({M:void 0===a.M?this.M:a.M,V:void 0===a.V?"requestSettings":a.V});for(var c=b;0<=c.lastIndexOf("/")&&"/"!==c;){b=a.filter(function(a){return a.name.toLowerCase()===d.toLowerCase()});b=L(b);for(var e=b.next();!e.done;e=b.next())if(e=e.value,(g.e.Z(e,"dimensions.adUnits")||[]).some(function(a){return a.toLowerCase()===c.toLowerCase()}))return[e];
c=c.substr(0,c.lastIndexOf("/"))}return[]};y.Object.defineProperties(a.prototype,{Ba:{configurable:!0,enumerable:!0,get:function(){var a="false"===g.e.nc("sbi_"+this.M)?!1:!0,b="*";this.aa.S&&(b=g.e.Da(this.aa.sa()));var c=1;"number"===typeof this.C.frequency&&(c=this.C.frequency);return a&&!this.C.disabled&&this.J(this.C,b,"platforms")&&this.H(this.C,"domain")&&Math.random()<=c}}});c.a=a},function(n,c,e){function a(a,b,d,c,e,k){this.id=a;this.D=Object(q.c)(b);this.R=d;this.G=e;this.Y=k;this.ea=[];
this.H=c;this.Ha=!1;this.ua=this.ua.bind(this);this.C=this.C.bind(this)}var q=e(0),b=e(1),h=e(2);a.prototype.C=function(){return this.ea.reduce(function(a,b){(a[b.K]=a[b.K]||[]).push(b);return a},{})};a.prototype.F=function(c,g,d){var f=this;return function(e){for(var k=[],h=0;h<arguments.length;++h)k[h-0]=arguments[h];k.forEach(function(e){e.db=2;g&&(e.I=Object(q.b)(e.I,g));e.Ia=Math.round(b.a.performance.now()-d);e.ma=!1;e=a.F(Object(q.i)("sbi_price_"+c.da.ja.name),e);f.Ha?(e.Ha=!0,f.Y.oa([e])):
c.Ka?(e.cc=!0,f.Y.oa([e])):f.ea.push(e)})}};a.prototype.ua=function(c){var e=this,d=Object(q.m)(function(){c(e.C())});b.a.setTimeout(function(){e.G.log("sbi",h.m);e.Ha=!0;d()},this.H);var f=0;this.D.forEach(function(c){var g=c.da,m=g.ja.Q.Ya({bb:"timeout"}),p=g.ja.Q.Ya({bb:"priceRules"}),n=Object(q.m)(function(){f+=1;f>=e.D.length&&d()});b.a.setTimeout(function(){e.G.log("sbi",h.d,[g.ja.name,m]);c.Ka=!0;n()},m);var l=b.a.performance.now(),u=a.C(g.ja.Q,e.R);0<Object.keys(u).length?g.Jc.then(function(){g.ja.fb(u,
e.id,e.F(c,p,l),n)}).catch(function(){n()}):n()})};c.a=a;a.D=function(a){return Object.keys(a).reduce(function(b,c){var d=a[c];d.uc()&&(b[c]=d);return b},{})};a.C=function(b,c){b=b.Ya({bb:"sizes"});var d={},e;for(e in c)c.hasOwnProperty(e)&&(d[e]=Object.assign({},c[e]),d[e].na=Object(q.f)(c[e].Ga(),b));return a.D(d)};a.F=function(a,b){a&&""!==b.qa&&0<b.I&&(b.I=parseInt(a,10));return b}},function(n,c,e){n=e(18);e=e(19);c.a={sonobi:new n.a(e.a)}},function(n,c,e){function a(a){this.caller=q.a;this.name=
a.name;this.Ta=a.Ta;this.hb=a.hb;this.fb=a.fb;this.parse=a.parse;this.Ca=a.Ca;this.Xa=a.Xa;this.done=Function;this.caller=q.a;this.Q=null;this.G={};this.D=Promise.resolve({});this.Pb=a.Pb;this.C=!1}var q=e(3),b=e(2);a.prototype.ua=function(a,c,e){this.C||(this.G=e,this.Q=a,this.C=!0,e.log("sbi",b.e,[this.name]),this.D=this.hb(a,c,e)||Promise.resolve({}));return this.D};c.a=a;a.Ca=function(a){return a}},function(n,c,e){function a(a){switch(a){case "href":return m.e.N().location;case "hash":return m.e.N().protocol+
m.e.N().host+m.e.N().pathname+m.e.N().la;case "search":return m.e.N().protocol+m.e.N().host+m.e.N().pathname+m.e.N().search;case "pathname":return m.e.N().protocol+m.e.N().host+m.e.N().pathname}}function q(a){var c=["hfa","cdf","ant","gmgt"].map(function(c){return b(a,c)}).filter(function(a){return a});c.push(h(a));return c.reduce(function(a,b){var c=b.gb;b=b.exec;var d="";"function"===typeof b&&(d=b(c));if(!d)return a;if("object"===typeof d||Array.isArray(d))d=JSON.stringify(d);return a+"&"+c.name.replace("_cookie_key",
"")+"="+encodeURIComponent(d)},"")}function b(a,b){var c=a.Fa({name:b});if(c)return{gb:c,exec:function(a){return m.e.Z(g.a,a.value)}};if(c=a.Fa({name:""+b+"_cookie_key"}))return{gb:c,exec:function(a){return m.e.zb(a.value)}}}function h(a){return{gb:{name:"vp"},exec:function(){return(m.e.Da(a.aa.sa())||"desktop").toLowerCase()}}}var m=e(0),g=e(1),d=e(20),f=e(2),p=e(21),k=e(22);c.a={hb:function(b,c,d){this.Q=b;this.Y=c;this.G=d;this.location=a(b.ha({name:"pageViewLocation"}));this.Eb=m.e.ub();this.ta=
new p.a(b);this.ta.hc();this.Nb=new k.a(b)},fb:function(b,c,e,k){function h(){return Promise.resolve()}var p=this,n={},l={},t={slots:{}},r=a(this.Q.ha({name:"pageViewLocation"}));r!==this.location&&(this.location=r,this.Eb=m.e.ub());var w=!1;for(A in b)if(null!=b[A]&&Object.keys(b[A]).length){r=b[A];var z=r.K+"|"+encodeURIComponent(r.O);w=this.Q.yc({K:b[A].K,Bb:"slot_override"})||[];if(0<w.length){var B=m.e.tc(m.e.Z(w[0],"dimensions.sizes"),r.na);if(0<B.length)w=this.ta.wb({sbi_ad:r.K,sbi_size:B}),
n[z]=B.join(",");else continue}else w=this.ta.wb({sbi_ad:r.K,sbi_size:r.na}),n[z]=r.na.join(",");w&&(t.slots[z]=w,delete n[z]);l[z]=new d.a(r.na[0],"sonobi","sonobi",A,r.K,this.Y,c)}c=q(this.Q);var A=this.Q.ha({name:"testUrl1"});r=this.Q.oc();A=A||r+"://apex.go.sonobi.com/trinity.json?key_maker=";var Q=m.e.Za(),I=this.Xa(A,n,c,this.Eb,g.a.sbi_morpheus.getReferrer("href"),this.Nb.value);I+=this.ta.Ba?"&or=1":"";this.G.log("sbi",f.c,["sonobi",b]);c=this.Q.Fa({name:"pubid"});null!=c&&null==m.e.zb("sbi_user_sync_complete")&&
(h=this.caller.Aa.bind(this.caller,"script",{src:"https://sync.go.sonobi.com/uc.js?pubid="+c.value}),c=new Date,c.setTime(Number(c)+12096E5),g.a.document.cookie="sbi_user_sync_complete=true; expires="+c.toUTCString()+"; path=/");this.G.log("sbi",f.c,["sonobi",b]);return h().then(function(){return Object.keys(n).length?p.caller.Sa(I,null,{withCredentials:!0}):"{}"}).then(JSON.parse).then(function(a){a.slots?Object.assign(a.slots,t.slots):(t.sbi_dc=p.ta.Mb,a=t);Array.isArray(a.sbi_px)&&a.sbi_px.forEach(function(a){p.caller.Aa(a.type,
{src:a.url})});p.G.log("sbi",f.b,["sonobi",b,a]);var c=m.e.mc(Q);a=p.parse.call(p,a,b,c,l);e.apply(null,[].concat(O(a)));k();return a})},parse:function(a,b,c,d){var e=[];if(a.slots)for(var k in b)if(null!=b[k]&&Object.keys(b[k]).length){var h=b[k],m=h.K+"|"+h.O,p=h.K+"|"+encodeURIComponent(h.O);if(m in a.slots){p=d[p];m=a.slots[m];"sbi_aid"in m||(m={sbi_aid:null,sbi_apoc:null,sbi_size:null});"sbi_dozer"in m||(m.sbi_dozer=!1);"sbi_pri"in m||(m.sbi_pri=10);"sbi_mouse"in m||(m.sbi_mouse=0,m.sbi_pri=
1);p.I=100*parseFloat(m.sbi_mouse);p.size=m.sbi_size||p.size;p.W=m.sbi_dozer;p.jb=m.sbi_ct||p.jb;p.ka=parseInt(m.sbi_pri,10);p.zc=c;p.Cb={sbi_aid:m.sbi_aid,sbi_dc:a.sbi_dc};var n=this.Q.ha({name:"testUrl2"})||"//%%sbi_dc%%apex.go.sonobi.com/sbi.js";p.qa=this.Ca(n+"?ref="+encodeURIComponent(g.a.sbi_morpheus.getReferrer("href"))+"&aid=%%sbi_aid%%&as=null","SCRIPT");p.$b=h.K;m.sbi_dozer&&(p.Va={sbi_dozer:m.sbi_dozer});e.push(p)}"sbi_suid"in a&&(this.Nb.value=a.sbi_suid)}this.G.log("sbi",f.a,["sonobi",
b,e]);return e},name:"sonobi",Ta:"sonobi",$c:b,Ad:"https://sync.go.sonobi.com/uc.js",Wc:a,Ca:m.e.ec,Xa:function(a,b,c,d,e,f){b=encodeURIComponent(JSON.stringify(b));e=encodeURIComponent(e);return""+a+b+c+"&pv="+d+"&ref="+e+(!1===f?"":"&suid="+f)+"&lib_name=3pdm&lib_v="+g.a.sbi_km.version}}},function(n,c,e){function a(a,c,e,g,d,f,p){this.mb=q.e.Za();this.J=g;this.La=d;this.Pa=0;this.Ma=e;this.nb=c;this.D="";this.Ra=a;this.ya={};this.Na="";this.F=10;this.C=-1;this.Qa=1;this.H={};this.Oa=p;this.xa=0;
this.L="display";this.ma=!1;this.db=1;"function"===typeof f.oa&&f.oa([this])}var q=e(0);a.prototype.ob=function(){return Object.assign(Object.create(this),this)};a.prototype.jc=function(){var a=this.ob(),c={buyerid:a.Ma,buyername:a.nb,adunit_code:a.La,pageViewId:a.Oa,bidid:a.mb,p:a.db,response:a.Qa,s:a.Ra||"0x0",bid:a.Pa,latency:a.xc,jsLatency:a.xa,auctionid:q.e.Z(a.ya,"sbi_aid"),datacenter:q.e.Z(a.ya,"sbi_dc")};a.W&&"string"===typeof a.W&&(c.dealid=a.Na);return c};y.Object.defineProperties(a.prototype,
{id:{configurable:!0,enumerable:!0,get:function(){return this.mb}},U:{configurable:!0,enumerable:!0,get:function(){return this.Oa},set:function(a){this.Oa=a}},K:{configurable:!0,enumerable:!0,get:function(){return this.J},set:function(a){this.J=a}},jb:{configurable:!0,enumerable:!0,get:function(){return this.L},set:function(a){this.L=a}},$b:{configurable:!0,enumerable:!0,get:function(){return this.La},set:function(a){this.La=a}},I:{configurable:!0,enumerable:!0,get:function(){return this.Pa},set:function(a){this.Pa=
a}},P:{configurable:!0,enumerable:!0,get:function(){return this.nb}},Cb:{configurable:!0,enumerable:!0,get:function(){return this.ya},set:function(a){this.ya=a}},xc:{configurable:!0,enumerable:!0,get:function(){return 0>=this.Ia||!this.Ia?-1:this.Ia},set:function(a){this.xa=Math.round(a)}},zc:{configurable:!0,enumerable:!0,get:function(){return 0>=this.C||!this.C?-1:Math.round(this.C)},set:function(a){this.C=Math.round(a)}},Ia:{configurable:!0,enumerable:!0,get:function(){return Math.round(this.xa)},
set:function(a){this.xa=Math.round(a)}},size:{configurable:!0,enumerable:!0,get:function(){return this.Ra},set:function(a){this.Ra=Array.isArray(a)?a.join("x"):a}},Ta:{configurable:!0,enumerable:!0,get:function(){return this.Ma},set:function(a){this.Ma=a}},qa:{configurable:!0,enumerable:!0,get:function(){return this.D},set:function(a){this.D=a}},W:{configurable:!0,enumerable:!0,get:function(){return this.Na},set:function(a){this.Na=a}},ka:{configurable:!0,enumerable:!0,get:function(){return this.F},
set:function(a){this.F=a}},Fc:{configurable:!0,enumerable:!0,get:function(){return this.Qa},set:function(a){this.Qa=a}},Va:{configurable:!0,enumerable:!0,get:function(){return this.H},set:function(a){this.H=a}}});c.a=a},function(n,c,e){function a(a){this.C=[];this.Mb="mco-1-";this.config=a;this.Ba=Number(this.config.ha({name:"oracle"})||0);this.F="https://apex.go.sonobi.com/oracle.json"}var q=e(3);a.prototype.wb=function(a){var b=this;return this.C.find(function(c,e){for(var d=0,f=Object.keys(a);d<
f.length;d++)if(void 0===c[f[d]]||c[f[d]]!==a[f[d]]&&!a[f[d]].includes(c[f[d]]))return!1;b.C.splice(e,1);return!0})};a.prototype.hc=function(){var a=this;this.Ba?q.a.Sa(this.F,void 0,{withCredentials:!0}).then(function(b){return(b=JSON.parse(b+""))&&Object.keys(b.slots).length?(a.Mb=b.sbi_dc,a.D(b)):{}}):Promise.resolve({})};a.prototype.D=function(a){var b=Object.keys(a.slots).map(function(b){var c=a.slots[b];b=b.split("|");c.sbi_ad=b[0];return c});return this.C=[].concat(O(b))};c.a=a},function(n,
c,e){function a(a){this.C=a.ha({name:"suidStorageStrategy"});this.D=!q.a.cb;this.L()}var q=e(1);a.prototype.J=function(a,c){var b=new Date,e=b.getTime();c*=6E4;b.setTime(c+e);b=b.toGMTString();a={value:a,expiryTimeMS:c+e};e=JSON.stringify(a);q.a.document.cookie="suid="+e+"; Expires="+b+"; Path=/";return a};a.prototype.F=function(){var a={},c=q.a.decodeURIComponent(q.a.document.cookie).split(";");c=L(c);for(var e=c.next();!e.done;e=c.next())if(e=e.value,0===e.trim().indexOf("suid=")){e=L(e.trim().split("="));
c=e.next().value;e=e.next().value;a[c]=e;break}return"suid"in a?JSON.parse(a.suid):!1};a.prototype.ca=function(a){a={value:a,expiryTimeMS:12096E5+Date.now()};q.a.cb.yd("suid",JSON.stringify(a));return a};a.prototype.H=function(){var a=JSON.parse(q.a.cb.hd("suid"));return a?a:!1};a.prototype.L=function(){var a=this.F();a&&a.expiryTimeMS<Date.now()&&this.U();this.D||(a=this.H())&&a.expiryTimeMS<Date.now()&&this.ba()};a.prototype.U=function(){this.J("",-20160)};a.prototype.ba=function(){q.a.cb.td("suid")};
y.Object.defineProperties(a.prototype,{value:{configurable:!0,enumerable:!0,get:function(){if("c"===this.C){var a=this.F();if(a)return a.value}else if("ls"===this.C){if(this.D)return!1;if(a=this.H())return a.value}return!1},set:function(a){if("c"===this.C)return this.J(a,20160);if("ls"===this.C)return this.D?void 0:this.ca(a)}}});c.a=a},function(n,c,e){function a(a,b){this.C=[];this.caller=q.a;this.G=a;this.D=b}var q=e(3),b=e(0),h=e(2),m=e(1),g=e(4),d={1:"BidRequested",2:"BidReceived",3:"BidRendered"},
f=["audienceNetwork"];a.prototype.F=function(a){var b=this;this.C.length||m.a.setTimeout(function(){b.J(b.C);b.C=[]},100);this.C.push(a)};a.prototype.H=function(a){var b=0;a.bc&&(b|=16);a.Ka&&(b|=8);a.lb&&(b|=4);a.ma&&(b|=2);switch(b){case 0:return 1;case 8:return 0;case 16:return 9;case 20:return 4;case 24:return 2;case 22:return 6;default:throw Error("Invalid bid status: "+b.toString(2)||"Assertion failed!");}};a.prototype.oa=function(a){a=L(a);for(var b=a.next();!b.done;b=a.next()){b=b.value;this.G.log("sbi",
h.g,[b.P,b]);var c={bc:0<b.I||b.W,Ka:b.Ha||b.cc,lb:b.lb,ma:b.ma},d=void 0;try{d=this.H(c),b.Fc=d}catch(B){this.G.log(h.o,[B.message])}this.F(b.jc())}};a.prototype.L=function(a){var c=b.e.vc(a,"buyername bid adunit_code s jsLatency bidid".split(" "));-1===f.indexOf(c.buyername)&&g.b.fa(d[a.p],c)};a.prototype.J=function(a){var c=void 0,d=this;c=void 0===c?this.D.ac.kc():c;a.forEach(function(a){return d.L(a)});if(c){var e=b.e.rc(a,"pageViewId");Object.keys(e).forEach(function(a){var f=e[a].map(function(a){return b.e.Ac(a,
["pageViewId"])});a=c+"?pageviewid="+a+"&corscred=1&ver="+m.a.sbi_km.version;f=JSON.stringify(f);return d.caller.Sa(a,f,{Db:"POST"}).catch(function(){})})}};c.a=a},function(n,c,e){var a=e(25),q=e(5),b=e(6);c.a=function(c){this.S=c;this.ac=new a.a(c);this.X=new q.a(c);this.aa=new b.a(c)}},function(n,c,e){function a(a){this.S=a.analyticsSettings;this.X=new q.a(a)}var q=e(5),b=e(0);a.prototype.kc=function(){var a=this.S.url;b.e.ab("url")&&!a&&(a=this.X.ga("url"));return a};c.a=a},function(n,c,e){c.a=
function(b,c,e,g,d,f){function h(){r=Object(a.j)();l[r]={qb:0,tb:0,Hb:[],Lb:[],Kb:[],Fb:!0};q.a.setTimeout(function(){l[r].Kb.forEach(function(a){return a()});l[r].Fb=!1},c.globalSettings.renderQueue)}function k(a){r&&l[r].Fb||h();l[r].Kb.push(a);l[r].qb++}function m(a,b){var c=l[a].Hb.push(b)-1;return function(b){l[a].tb++;l[a].Lb[c]=b;l[a].tb===l[a].qb&&n(a)}}function n(a){l[a].Hb.forEach(function(b,c){b(l[a].Lb[c])})}var l={},r;return{Ec:function(h,n){q.a.sbi_morpheus.initialized||q.a.sbi_morpheus.initialize();
if(Object.keys(h).length){var l=Object(a.j)(),p=Object(a.m)(function(a){var c=Object.keys(a).map(function(b){return a[b]});c.length?(g.Ic(b.qc(c,d.X.ga("priceRules")||[],d.X.ga("sendAllKeys")||!1)),c=c.map(function(a){return a.ob()}),c.length&&(c=c.map(function(a){a.K=h[a.K].K;return a}),f.oa(c),n())):n()});0<c.globalSettings.renderQueue?k(function(){return b.Jb(h,e,l,m(r,p))}):b.Jb(h,e,l,p)}},nd:h,Yc:k,ad:m,sd:n,vd:l,ud:r}};var a=e(0),q=e(1)},function(n,c,e){var a=e(1),l=e(4),b=e(0);c.a=function(){var c=
a.a.sbi_morpheus&&a.a.sbi_morpheus.cmd?a.a.sbi_morpheus.cmd:[],e=Object.assign(a.a.sbi_morpheus||{},{registration:{},register:function(){},enableReactiveSizes:function(){},callOperator:function(){},initialized:!1,initialize:function(){for(;0<c.length;)try{c.shift()()}catch(g){}e.initialized=!0},cmd:function(){var b=[],c=b.push;b.push=function(d){for(var e=[],f=0;f<arguments.length;++f)e[f-0]=arguments[f];return a.a.sbi_morpheus.initialized?e.reduce(function(a,b){try{b()}catch(B){}a++;return a},0):
c.apply(b,e)};return b}(),addEventListener:function(a,b){return l.b.T(a,b)},removeEventListener:function(a,b){return l.b.Dc(a,b)},setReferrer:function(a){this.Zb=b.e.N(a)},getReferrer:function(a){a=void 0===a?"href":a;return b.e.Z(this.Zb,a)||b.e.N()[a]}});return e}},function(n,c,e){function a(a,c,e){var d=this;this.F=l;this.H=b;this.L=function(a){if("SBI_SLOT_TARGETING"===a.data.key&&a.source)try{var b=Object.keys(d.D.R).map(function(a){return d.D.R[a]}).find(function(b){return b.gc===a.source.frameElement.id}).kb.Ja;
a.source.postMessage({message:"SBI_HOLLABACK",macros:b},Object(m.h)())}catch(z){}};this.F=l;this.H=b;this.C=this.C.bind(this);this.da=a;this.D=c;this.J=e}function l(a){"SAFE_FRAME_RENDER"===a.data.key&&a.source&&h.a.sbi_km.API.render(a.source,a.data.id,a.data.macros,a.origin)}function b(a){"SBI_KM_LOOKUP"===a.data.key&&a.source&&a.data.id===h.a.sbi_km.id&&a.source.postMessage({key:"SBI_KM_LOOKUP_RESPONSE"},a.origin)}var h=e(1),m=e(0);a.prototype.C=function(a){this.F(a);this.H(a);this.J.X.ga("enablePassback")&&
this.L(a)};a.prototype.Cc=function(){h.a.addEventListener("message",this.C,!1)};c.a=a}])})({url:"//mtrx.go.sonobi.com",adServer:"dfp",globalSettings:{sizes:"300x250 300x600 300x1050 300x50 320x50 320x100 728x90 160x600 120x600 970x250 970x90 300x100 970x66".split(" "),timeout:2E3,priceRules:[{ge:5E3,set:5E3},{ge:3E3,lt:5E3,round:10},{ge:900,lt:3E3,round:5},{lt:900,round:1}],supportResizing:!0},adapterSettings:[{name:"sonobi",sizes:"300x250 300x600 300x1050 300x50 320x50 320x100 728x90 160x600 120x600 970x250 970x90 300x100 970x66".split(" "),
timeout:2500,disabled:!1,platforms:["mobile","desktop","tablet"],priceRules:[],parseSettings:[],requestSettings:[]}],platformSettings:{mobile:{viewport:{lt:768}},tablet:{viewport:{ge:768,lt:992}},desktop:{viewport:{ge:992}}},analyticsSettings:{url:"https://keymaker.go.sonobi.com/keymaker",timeout:2E3}},"3.29.2");}).call(window);

//# sourceMappingURL=http://mtrx.go.sonobi.com/morpheus.myspace.1592.js.map